#!/bin/bash
# git mis-behaves if you develop on Windows.  Need to explicitly define executables for shell scripts
#

for f in lab2/wrap-mysql lab3/trigger-lambda lab1/init-params.py lab1/fix-permissions
do
  echo git update-index --chmod=+x $f
done

