#!/bin/bash
# git mis-behaves if you develop on Windows.  Need to explicitly define executables for shell scripts
#

for f in wrap-mysql trigger-lambda init/init-params.py
do
  echo git update-index --chmod=+x $f
done

