#!/bin/bash
# host=devdbcluster-p2.cluster-cjdii2k9xlvv.us-east-2.rds.amazonaws.com

# Get the database name from cloudformation export
host=$(aws cloudformation list-exports --query 'Exports[][Name,Value]' --output text | grep DevDB-Endpoint | cut -f 2)
echo host: $host
# Get login and password information from parameter store
user=$(aws ssm get-parameter --name /mydb/Dev/Login --query Parameter.Value  --output text)
password=$(aws ssm get-parameter --name /mydb/Dev/Password --query Parameter.Value  --output text)

echo user: $user
echo password: $password

# set the password as MySQL default password
# by creating a new $HOME/.my.cnf
cat - > ~/.my.cnf << EOF
[client]
password=$password
EOF
mysql -u $user -h $host 
